### ISSUE TITLE
Schedulers.io() or Schedulers.computation()

### ISSUE THREAD

**Issue by vicgrad** [pwittchen/ReactiveSensors#19]
In the sample (SensorHelper.java) I see you're using Schedulers.io().

Wouldn't it be better to use Schedulers.computation() for this?

ref: http://reactivex.io/RxJava/javadoc/rx/schedulers/Schedulers.html

**Comment by pwittchen** [comment]
Hi,

Thank you for creating new issue. 

I'm not sure about this. Library is responsible for reading data from sensors, so it can be considered as I/O work. There's no additional heavy operations in the library under the hood. If I understand RxJava schedulers correctly, we should use `Schedulers.computation()` in case of performing some computations.

I'm open for discussion and if you provide good arguments about switching to `Schedulers.computation()` in this case, we can update samples. :)

**Comment by vicgrad** [comment]
Hello,

Well, I would say Scheduler.io() should be use when there are blocking calls in the subscription (network, storage, etc). Here, the blocking stuff is happening in the Android API, you are basically building the observable over the SensorEventListener calls. 
Basically, I think in this case what will be executed on the io thread is the content of the call method in the Observable.OnSubscribe class, right?

Here is another link on the subject:
http://stackoverflow.com/questions/31276164/rxjava-schedulers-use-cases

**Comment by pwittchen** [comment]
Yeah. I think, you're right. Description in StackOverflow thread explains a lot. Actually, It should work properly even if we use current thread (`Schedulers.immediate()`), because as you wrote, blocking stuff was handled in Android API. Moreover, intention of this project was simplifying of processing sensor data rather than dealing with multi-threading.

Nevertheless, to keep the solution right and consistent with RxJava documentation, I'll update code samples.

**Comment by pwittchen** [comment]
I've changed `Schedulers.io()` to `Schedulers.computation()` in sample apps and documentation in https://github.com/pwittchen/ReactiveSensors/commit/315b850d94d88ed3bd59ef71c111f70ef8131ed4.
